"""initial_migration

Revision ID: ffcac774ef68
Revises: 
Create Date: 2026-01-28 10:02:59.781478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffcac774ef68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('POST', 'STORY', 'REEL', name='contenttype'), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('score >= 0.0 AND score <= 10.0', name='check_score_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_recommendations_content', 'ai_recommendations', ['content_id', 'content_type'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_content_id'), 'ai_recommendations', ['content_id'], unique=False)
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('posts_count', sa.Integer(), nullable=False),
    sa.Column('avg_engagement', sa.Float(), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('avg_engagement >= 0.0', name='check_avg_engagement_positive'),
    sa.CheckConstraint('followers >= 0', name='check_followers_positive'),
    sa.CheckConstraint('posts_count >= 0', name='check_posts_count_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_competitors_last_checked', 'competitors', ['last_checked'], unique=False)
    op.create_index('idx_competitors_username', 'competitors', ['username'], unique=False)
    op.create_index(op.f('ix_competitors_username'), 'competitors', ['username'], unique=True)
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('posts_count', sa.Integer(), nullable=False),
    sa.Column('stories_count', sa.Integer(), nullable=False),
    sa.Column('reels_count', sa.Integer(), nullable=False),
    sa.Column('total_likes', sa.Integer(), nullable=False),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.Column('total_views', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('engagement_rate >= 0.0', name='check_engagement_rate_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_stats_date', 'daily_stats', ['date'], unique=False)
    op.create_index(op.f('ix_daily_stats_date'), 'daily_stats', ['date'], unique=True)
    op.create_table('hashtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('avg_likes', sa.Float(), nullable=False),
    sa.Column('avg_comments', sa.Float(), nullable=False),
    sa.Column('effectiveness_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('avg_comments >= 0.0', name='check_avg_comments_positive'),
    sa.CheckConstraint('avg_likes >= 0.0', name='check_avg_likes_positive'),
    sa.CheckConstraint('effectiveness_score >= 0.0', name='check_effectiveness_score_positive'),
    sa.CheckConstraint('usage_count >= 0', name='check_usage_count_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hashtags_effectiveness', 'hashtags', ['effectiveness_score'], unique=False)
    op.create_index('idx_hashtags_tag', 'hashtags', ['tag'], unique=False)
    op.create_index(op.f('ix_hashtags_tag'), 'hashtags', ['tag'], unique=True)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instagram_id', sa.String(length=255), nullable=False),
    sa.Column('post_type', sa.Enum('PHOTO', 'VIDEO', 'CAROUSEL', name='posttype'), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_posts_instagram_id', 'posts', ['instagram_id'], unique=False)
    op.create_index('idx_posts_posted_at', 'posts', ['posted_at'], unique=False)
    op.create_index(op.f('ix_posts_instagram_id'), 'posts', ['instagram_id'], unique=True)
    op.create_index(op.f('ix_posts_posted_at'), 'posts', ['posted_at'], unique=False)
    op.create_table('reels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instagram_id', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('plays', sa.Integer(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reels_instagram_id', 'reels', ['instagram_id'], unique=False)
    op.create_index('idx_reels_posted_at', 'reels', ['posted_at'], unique=False)
    op.create_index(op.f('ix_reels_instagram_id'), 'reels', ['instagram_id'], unique=True)
    op.create_index(op.f('ix_reels_posted_at'), 'reels', ['posted_at'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instagram_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('replies', sa.Integer(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stories_instagram_id', 'stories', ['instagram_id'], unique=False)
    op.create_index('idx_stories_posted_at', 'stories', ['posted_at'], unique=False)
    op.create_index(op.f('ix_stories_instagram_id'), 'stories', ['instagram_id'], unique=True)
    op.create_index(op.f('ix_stories_posted_at'), 'stories', ['posted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_posted_at'), table_name='stories')
    op.drop_index(op.f('ix_stories_instagram_id'), table_name='stories')
    op.drop_index('idx_stories_posted_at', table_name='stories')
    op.drop_index('idx_stories_instagram_id', table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_reels_posted_at'), table_name='reels')
    op.drop_index(op.f('ix_reels_instagram_id'), table_name='reels')
    op.drop_index('idx_reels_posted_at', table_name='reels')
    op.drop_index('idx_reels_instagram_id', table_name='reels')
    op.drop_table('reels')
    op.drop_index(op.f('ix_posts_posted_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_instagram_id'), table_name='posts')
    op.drop_index('idx_posts_posted_at', table_name='posts')
    op.drop_index('idx_posts_instagram_id', table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_hashtags_tag'), table_name='hashtags')
    op.drop_index('idx_hashtags_tag', table_name='hashtags')
    op.drop_index('idx_hashtags_effectiveness', table_name='hashtags')
    op.drop_table('hashtags')
    op.drop_index(op.f('ix_daily_stats_date'), table_name='daily_stats')
    op.drop_index('idx_daily_stats_date', table_name='daily_stats')
    op.drop_table('daily_stats')
    op.drop_index(op.f('ix_competitors_username'), table_name='competitors')
    op.drop_index('idx_competitors_username', table_name='competitors')
    op.drop_index('idx_competitors_last_checked', table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_ai_recommendations_content_id'), table_name='ai_recommendations')
    op.drop_index('idx_ai_recommendations_content', table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    # ### end Alembic commands ###
